name: Build & Push customized Coolify

on:
  push:
    branches: ["main", "build-push"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "coollabsio/coolify"

permissions:
  contents: read
  packages: write

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: version
        run: |
          VERSION=$(docker run --rm -v "$(pwd):/app" -w /app php:8.2-alpine3.16 php bootstrap/getVersion.php)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build image and push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/prod/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}